### PR TITLE
Project fixes and ondraw correction + Material ripples

### PR DESCRIPTION
**Pull request by dabluck**
There is an issue where the library is instantiating objects unnecessarily in the ondraw method. This corrects that.

Also added ripples to the press state on 21+. I thought about making them optional but who doesn't like ripples? Most people use this library for the material feel right? Let me know your thoughts.

Also took the liberty of updating to api 22 and removing ant project files, not sure what they're still doing in the repository.

Thanks!

### CODE REVIEW

**Comment by dabluck** [comment]
Didn't see somebody had already added ripples. If you like his way better let me know

**Comment by jaredsburrows** [comment]
How do you turn the ripples on? I do not see any ripples like I see in https://github.com/pizza/MaterialTabs?

**Comment by jpardogo** [comment]
In the next version ripples default selector for api 21+. If you want ripples below API 21 you will need to use custom tabs. Like in the sample

**Comment by jaredsburrows** [comment]
That is exactly what I wanted. I am excited for `1.1.0`.

**Pull request closed without merging**
