### PR TITLE
Fix for #148

### PR DESCRIPTION
**Pull request by HeinrichReimer**
Fix for #148

### CODE REVIEW

**Comment by HeinrichReimer** [comment]
@jpardogo Please merge this fix. I need that for an app I'm working on.

**Comment by jpardogo** [comment]
If I have time this week I will try to review several open PR's as well as issues and then release a new version of the library as soon as I am happy with the changes. Many thanks.

**Comment by HeinrichReimer** [comment]
Thanks!

**Comment by jpardogo** [comment]
Merged in dev branch for next release

**Pull request closed without merging**
