### PR TITLE
Annotations to suppress deprecation and target API warnings

### PR DESCRIPTION
**Pull request by mstevens83**
Added annotations to suppress deprecation and target API warnings on the `OnGlobalLayoutListener`

### CODE REVIEW

**Comment by ataulm** [comment]
:+1:

**Comment by jpardogo** [comment]
Thanks for the PR I will review it asap

**Comment by mstevens83** [comment]
Just so you know: the target API warning was actually a compiler error in eclipse. So at least in eclipse that annotation seems required.

**Comment by jpardogo** [comment]
Merged into dev branch. Cheers

**Pull request closed without merging**
